version: '3.9'

services:
  database:
    container_name: postgres_container
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: ./.env
    ports:
      - '5432:5432'
    restart: unless-stopped

volumes:
  postgres:
