###################
# BUILD FOR LOCAL DEVELOPMENT
###################

FROM node:18-alpine
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn install
COPY . .

RUN npx prisma migrate dev init

# Start the server using the production build
CMD [ "yarn", "start:dev" ]