version: '3.9'

services:
  database:
    container_name: postgres_container
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ./.env
    ports:
      - '5432:5432'
    restart: unless-stopped

  nest-app:
    container_name: nestjs_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    env_file: ./.env
    depends_on:
      - database
    command: npm run start:dev
    restart: unless-stopped

volumes:
  postgres_data:
